# General simulation settings
simulation:
  map_yaml_file: "config/maps/square_5x5.yaml"       # OpenAI Gym environment name
  agent_yaml_file: "config/agents/expert/test.yaml" # Agents in the simulation
  ontology_yaml_file: "config/rules/ontology_full.yaml" # Ontology of the simulation
  rule_type: "Z3"               # z3 
  rule_yaml_file: "config/rules/sim/expert/expert_rule_discriminative.yaml"
  rl: false
  debug: false
  use_multi: false
  enable_gna: true
  gna_top_k: 3
  gna_selection_mode: semantic_lna
  gna_top_k1: 3
  gna_top_k2: 5
  enable_subrule_analysis: true  # Enable sub-rule satisfiability analysis
  enable_sim_metrics: true
  agent_region: 70
  




