# General simulation settings
simulation:
  map_yaml_file: "config/maps/square_5x5.yaml"       # OpenAI Gym environment name
  agent_yaml_file: "full_experiments_20260401_210122/agents/agents_20c_8p.yaml"
  ontology_yaml_file: "config/rules/ontology_full.yaml" # Ontology of the simulation
  rule_type: "Z3"               # z3 
  rule_yaml_file: "config/rules/sim/expert/expert_rule_discriminative.yaml"
  rl: false
  debug: false
  use_multi: false
  enable_gna: true
  gna_top_k: 1
  gna_selection_mode: semantic_random
  gna_top_k1: 0
  gna_top_k2: 0
  enable_subrule_analysis: true  # Enable sub-rule satisfiability analysis
  enable_sim_metrics: true
  agent_region: 50
  




